name: Fetch latest info from APIs

on:
 schedule:
  - cron: "0 */8 * * *" # Runs every 8 hours (UTC)
 workflow_dispatch: # Allows manual execution

jobs:
 run-script:
  runs-on: ubuntu-latest

  env:
   STEAMWEBAPI_KEY: ${{vars.STEAMWEBAPI_KEY }}

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Set up Deno
     uses: denoland/setup-deno@v2
     with:
      deno-version: v2.x

   - name: Run tradeup script
     run: deno run --allow-net --allow-read --allow-write --allow-env tradeuptracker/logic.ts ${{ vars.STEAMWEBAPI_KEY }} true
